# Generated by Django 4.1.3 on 2023-03-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('conmpany_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=50, verbose_name='Title')),
                ('description', models.CharField(default='name', max_length=50, verbose_name='Info')),
                ('new', models.CharField(default='nw', max_length=200)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Not it ', 'Not it'), ('stocks', 'stocks')], default='name', max_length=100)),
                ('added_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='Title')),
                ('address', models.CharField(default='name', max_length=50, verbose_name='Street')),
                ('position', models.CharField(choices=[('manager', 'manager'), ('Seniormanger', 'seniormanager'), ('cheifofficer', 'cheifofficer')], default='name', max_length=50, verbose_name='Title')),
                ('about', models.CharField(default='name', max_length=100, verbose_name='Description')),
                ('number', models.CharField(default='name', max_length=8, verbose_name='Number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
