# Generated by Django 4.1.3 on 2023-03-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='Name'),
        ),
    ]
